[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.28.1", features = ["rt","rt-multi-thread", "macros"]}
torrent-search-client = {path = "../torrent-search-client", version = "0.1"}
