[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
torrent-search-client = {path = "../torrent-search-client", version = "0.1"}
rocket = { version = "=0.5.0-rc.3",  features=["json"]}