[package]
name = "qbittorrent-api"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils", version = "0.1" }
derive-getters = "0.3.0"
derive_setters = "0.1.6"
serde = "1.0.194"
serde_json = "1.0.110"
surf = { version = "2.3.2", features = [
	"curl-client",
	"encoding",
], default-features = false }
juniper = { version = "0.15.12", optional = true }
chrono = "0.4.31"
log = "0.4.20"

[features]
graphql = ["dep:juniper"]
