[package]
name = "torrent-search-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
bytesize = "1.2.0"
chrono = "0.4.26"
derive-getters = "0.3.0"
futures = "0.3.28"
http-cache-reqwest = "0.9.0"
lazy_static = "1.4.0"
regex = "1.8.4"
reqwest = "0.11.17"
reqwest-middleware = "0.2.2"
scraper = "0.16.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.96"
task-local-extensions = "0.1.4"
urlencoding = "2.1.2"
