[package]
name = "torrent-search-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils", version = "0.1" }
async-trait = "0.1.77"
bytesize = "1.3.0"
chrono = "0.4.31"
derive-getters = "0.3.0"
distance = "0.4.0"
futures = "0.3.30"
http-cache-reqwest = "0.9.0"
juniper = { version = "0.15.12", optional = true }
lazy_static = "1.4.0"
regex = "1.10.2"
reqwest = "0.11.23"
reqwest-middleware = "0.2.4"
scraper = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.110"
task-local-extensions = "0.1.4"
urlencoding = "2.1.3"

[features]
graphql = ["dep:juniper"]
