[package]
name = "torrent-search-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils", version = "0.1" }
async-trait = "0.1.77"
bytesize = "1.3.0"
chrono = "0.4.31"
derive-getters = "0.3.0"
distance = "0.4.0"
futures = "0.3.30"
juniper = { version = "0.15.12", optional = true }
lazy_static = "1.4.0"
regex = "1.10.2"
scraper = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.110"
task-local-extensions = "0.1.4"
urlencoding = "2.1.3"
surf = { version = "2.3.2", features = [
	"curl-client",
	"encoding",
], default-features = false }
http-cache-surf = "0.12.1"
log = "0.4.20"

[features]
graphql = ["dep:juniper"]

[dev-dependencies]
tokio = "1.36.0"
