name: Update Docker Hub Description
on:
    push:
        branches:
            - main
        paths:
            - README.md
            - .github/workflows/dockerhub-description.yml
jobs:
    dockerHubDescription:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v2
              with:
                  username: netfloex
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  repository: netfloex/torrent-api
                  short-description: ${{ github.event.repository.description }}
