name: Build server

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Application
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: 1.65.0
                  override: true

            - name: Cargo Fetch
              run: cargo fetch --locked

            - name: Cargo Build
              run: cargo build --release

            - uses: actions/upload-artifact@v3
              name: Upload result
              with:
                  name: api-server
                  path: target/release/api-server
