name: Build and push

on:
    push:

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              run: rustup toolchain install 1.86.0 --profile minimal

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: |
                      api-server
                      torrent-search-client
                      qbittorrent-api
                      utils
                      movie-info

            - name: Cargo Fetch
              run: cargo fetch --locked

            - name: Test
              run: cargo test --locked

    docker:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: amd64
                    - os: ubuntu-24.04-arm
                      arch: arm64

        runs-on: ${{ matrix.os }}
        needs: tests

        steps:
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ${{ vars.REGISTRY_IMAGE }}
                  tags: |
                      type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
                      type=semver,pattern=v{{major}}.{{minor}}
                      type=semver,pattern=v{{major}}
                      type=raw,value=latest

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push by digest
              id: build
              uses: docker/build-push-action@v5
              with:
                  platforms: ${{ matrix.arch }}
                  labels: ${{ steps.meta.outputs.labels }}
                  outputs: type=image,name=${{ vars.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Export digest
              run: |
                  mkdir -p /tmp/digests
                  digest="${{ steps.build.outputs.digest }}"
                  touch "/tmp/digests/${digest#sha256:}"

                  # Create platform variable with a / changed to - (e.g. linux/amd64 to linux-amd64)
                  platform=linux/${{ matrix.arch }}
                  echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

            - name: Upload digest
              uses: actions/upload-artifact@v4
              with:
                  name: digests-${{ env.PLATFORM_PAIR }}
                  path: /tmp/digests/*
                  if-no-files-found: error
                  retention-days: 1
    merge:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Download digests
              uses: actions/download-artifact@v4
              with:
                  path: /tmp/digests
                  pattern: digests-*
                  merge-multiple: true

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ vars.REGISTRY_IMAGE }}
                  tags: |
                      type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
                      type=semver,pattern=v{{major}}.{{minor}}
                      type=semver,pattern=v{{major}}
                      type=raw,value=latest

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Create manifest list and push
              working-directory: /tmp/digests
              run: |
                  docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
                    $(printf '${{ vars.REGISTRY_IMAGE }}@sha256:%s ' *)
